version: '3'
services:
  web:
    build: ./allSpice
    image: nmoehlmann/allspice:latest
    ports:
      - "7045:7045"

# version: '3'
# services:
#   frontend:
#   build: ./allSpice.client
#   ports:
#     - "7045:7045"
#   container_name: frontend-docker
#   restart: always
#   links:
#     - backend

#   backend:
#     build: ./allSpice
#     ports:
#       - "80:80"
#     container_name: backend-docker
#     restart: always